-- 1. Create the table
CREATE TABLE menu_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  name text not null,
  email text not null,
  room text not null,
  menu_feedback jsonb not null
);

-- 2. Add the unique constraint on the email column
ALTER TABLE menu_submissions
ADD CONSTRAINT unique_email UNIQUE (email);

-- 3. Enable Row Level Security (RLS)
-- This is a good practice for Supabase to secure your data.
-- By default, no one can access the data. You need to create policies.
ALTER TABLE menu_submissions ENABLE ROW LEVEL SECURITY;

-- 4. Create a policy to allow public read access (for the dashboard)
-- This is just an example. You might want to restrict this further.
CREATE POLICY "Public read access for dashboard"
ON menu_submissions
FOR SELECT
USING (true);

-- 5. Create a policy to allow users to insert their own submissions
-- This assumes you are using Supabase Auth and the user is authenticated.
-- If you are not using Supabase Auth, you might need a different policy.
CREATE POLICY "Allow users to insert their own submission"
ON menu_submissions
FOR INSERT
WITH CHECK (true);
